export interface ReadingDay {
  day: number;
  title: string;
  ornamentName: string;
  bibleVerses: string;
  readingText: string[];
}

export const readings: ReadingDay[] = [
  {
    day: 1,
    title: 'Creation of Universe',
    ornamentName: 'Sun',
    bibleVerses: 'Genesis 1-2:4',
    readingText: [
      `In the beginning God made heaven and earth. The earth was invisible and unfinished; and darkness was over the deep. The Spirit of God was hovering over the face of the water. Then God said, “Let there be light”; and there was light. God saw the light; it was good; and God divided the light from the darkness. God called the light Day; the darkness He called Night; and there was evening and morning, one day.`,
      `Then God said, “Let there be a firmament in the midst of the water, and let it divide the water from the water”; and it was so. Thus God made the firmament, and God divided the water under the firmament from the water above the firmament. So God called the firmament Heaven, and God saw that it was good; and there was evening and morning, the second day.`,
      `Then God said, “Let the water under heaven be gathered together into one place, and let the dry land appear”; and it was so. The water under heaven was gathered into its places, and the dry land appeared. So God called the dry land Earth, and the gathering together of the waters He called Seas; and God saw that it was good. Then God said, “Let the earth bring forth the herb of grass, bearing seed according to its kind and likeness. Let the fruit tree bear fruit, whose seed is in itself according to its kind on earth.” It was so. Thus the earth brought forth the herb of grass, bearing seed according to its kind and likeness. The fruit tree bore fruit, whose seed is in itself according to its kind on earth. God saw that it was good. So evening and morning were the third day.`,
      `Then God said, “Let there be lights in the firmament of heaven for illumination to divide day from night. Let them be for signs and seasons, and for days and years. Let them be for illumination in the firmament of heaven to give light on the earth.” It was so. Then God made two great lights: the greater light to rule the day, and the lesser light to rule the night. He made the stars also. God set them in the firmament of heaven to give light on the earth, and to rule over the day and over the night, and to divide the light from the darkness. God saw that it was good. So evening and morning were the fourth day.`,
      `Then God said, “Let the waters bring forth creatures having life, and let birds fly above the earth across the face of heaven's firmament.” It was so. Thus God made great sea creatures and every living thing that moves with which the waters abounded, according to their kind, and every winged bird according to its kind. God saw that it was good. God blessed them, saying, “Be fruitful and multiply, and fill the waters in the seas, and let birds multiply on earth.” So evening and morning were the fifth day.`,
      `Then God said, “Let the earth bring forth the living creature according to its kind: the quadrupeds, the creeping things, and the wild animals of the earth according to their kind.” It was so. So God made the wild animals of the earth according to their kind, the cattle according to their kind, and all the creeping things on earth according to their kind. God saw that it was good. Then God said, “Let Us make man in Our image, according to Our likeness. Let them have dominion over the fish of the sea, over the birds of heaven, over the cattle, and over all the earth, and over every creeping thing that moves on the earth.” So God made man; in the image of God He made him; male and female He made them. Then God blessed them; and God said to them, “Be fruitful and multiply; fill the earth and subdue it, and have dominion over the fish of the sea, over the birds of heaven, and over every living thing that moves on the earth.”`,
      `Then God said, “Behold, I have given you every seed-bearing herb that sows seed on the face of all the earth, and every tree whose fruit yields seed; to you it shall be for food. I also give every green plant as food for all the wild animals of the earth, for all the birds of heaven, and for everything that creeps on the earth in which is the breath of life.” It was so. Then God saw everything He had made, and indeed, it was very good. So evening and morning were the sixth day.`,
      `Thus heaven and earth and all their adornment were finished. And on the seventh day God finished the works He made, and He rested on the seventh day from all the works He made. Then God blessed the seventh day and sanctified it, because in it He rested from all His works God began to make.`,
      `This is the book of the genesis of heaven and earth when they were made, in the day the Lord God made heaven and earth`,
    ],
  },
  {
    day: 2,
    title: 'Creation of Man',
    ornamentName: 'Two People',
    bibleVerses: 'Genesis 2:4-25',
    readingText: [
      `This is the book of the genesis of heaven and earth when they were made, in the day the Lord God made heaven and earth, before any plant of the field was on earth and before any herb of the field sprang up. For God had not sent rain on the earth, and there was no man to till the ground; but a fountain came up from the ground and watered the whole face of the earth. Then God formed man out of dust from the ground, and breathed in his face the breath of life; and man became a living soul.`,
      `Then the Lord God planted a garden eastward in Eden, and there He put the man He formed. Besides this, God caused every tree beautiful to the sight and good for food to grow from the ground. Also, in the middle of the garden were the tree of life and the tree of learning the knowledge of good and evil. Now a river went out of Eden to water the garden, and from there it separated into four heads. The name of the first is Pishon. It circles all the land of Havilah, where there is gold. And the gold of that land is good. The carbuncle and the emerald are there as well. The name of the second river is Gihon. It circles all the land of Ethiopia. The name of the third river is Tigris. It flows over against the Assyrians. And the fourth river is Euphrates.`,
      `Then the Lord God took the man He formed and put him in the garden to tend and keep it. And the Lord God commanded Adam, saying, “You may eat food from every tree in the garden; but from the tree of the knowledge of good and evil you may not eat; for in whatever day you eat from it, you shall die by death.”`,
      `And the Lord God said, “It is not good for man to be alone. I will make him a helper comparable to him.” Also, God formed out of the ground all the wild animals of the field and all the birds of heaven, and brought them to Adam to see what he would call them. Thus whatever Adam called each living creature, that was its name. So Adam gave names to all the cattle, to all the birds of heaven, and to all the wild animals of the field. But for Adam there was not found a helper comparable to him. Thus God brought a trance upon Adam, and he slept; and He took one of his ribs, and filled up the flesh in its place. Then the Lord God built the rib He took from Adam into a woman, and brought her to him. So Adam said, “This is now bone of my bones, and flesh of my flesh. She shall be called Woman, because she was taken out of Man. For this reason a man shall leave his father and mother and be joined to his wife; and the two shall become one flesh.” Now the two were naked, both Adam and his wife, and were not ashamed.`,
    ],
  },
  {
    day: 3,
    title: 'The Fall',
    ornamentName: 'Fruit',
    bibleVerses: 'Genesis 3:1-24',
    readingText: [
      `Now the serpent was more cunning than all the wild animals the Lord God made on the earth. And he said to the woman, “Has God indeed said, ‘You shall not eat from every tree of the garden’?” And the woman said to the serpent, “We may eat the fruit from the trees of the garden; but from the fruit of the tree in the middle of the garden, God said, ‘You shall not eat from it, nor shall you touch it, lest you die.’ ” Then the serpent said to the woman, “You shall not die by death. For God knows in the day you eat from it your eyes will be opened, and you will be like gods, knowing good and evil.” So when the woman saw the tree was good for food, was pleasant to the eyes, and a tree beautiful to contemplate, she took its fruit and ate. She also gave it to her husband with her, and he ate. Then the eyes of the two were opened, and they knew they were naked. So they sewed fig leaves together and made themselves coverings.`,
      `Then they heard the voice of the Lord God walking in the garden that afternoon, and Adam and his wife hid themselves within the tree in the middle of the garden from the presence of the Lord God. So the Lord God called Adam and said to him, “Adam, where are you?” He replied, “I heard Your voice as You were walking in the garden, and I was afraid because I was naked; so I hid myself.” Thus He said, “Who said you were naked? Have you eaten from the one tree from which I commanded you not to eat?” Then Adam said, “The woman You gave me, gave me of the tree, and I ate.” So the Lord God said to the woman, “What is this you have done?” The woman said, “The serpent deceived me, and I ate.” Thus the Lord God said to the serpent, “Because you have done this, you are cursed more than all cattle, and more than all the wild animals of the earth. On your breast and belly you shall go, and you shall eat dust all the days of your life. I will put enmity between you and the woman, and between your seed and her seed. He shall bruise your head, and you shall be on guard for His heel.”`,
      `To the woman He said, “I will greatly multiply your pain and your groaning, and in pain you shall bring forth children. Your recourse will be to your husband, and he shall rule over you.” Then to Adam He said, “Because you heeded the voice of your wife, and ate from the one tree of which I commanded you, saying, ‘You shall not eat from it,’ cursed is the ground in your labors. In toil you shall eat from it all the days of your life. Both thorns and thistles it shall bring forth for you, and you shall eat the herb of the field. In the sweat of your face you shall eat bread till you return to the ground from which you were taken. Earth you are, and to earth you shall return.” So Adam called his wife's name Life, because she was the mother of all living.`,
      `Also for Adam and his wife the Lord God made garments of skin, and clothed them. Then the Lord God said, “Behold, the man has become like one of Us, to know good and evil. Now, lest he put out his hand and take also of the tree of life, and eat, and live forever—” therefore the Lord God sent him out of the garden of pleasure to cultivate the ground from which he was taken. So He cast out Adam, and made him dwell opposite the garden of pleasure. He then stationed the cherubim and the fiery sword which turns every way to guard the way to the tree of life.`,
    ],
  },
  {
    day: 4,
    title: 'Noah',
    ornamentName: 'Rainbow',
    bibleVerses: 'Genesis 6:9-7:6, 7:11-24, 8:1-24',
    readingText: [
      `This is the genealogy of Noah. Noah was a righteous man, who was perfect in his generation and well-pleasing to God. So Noah begot three sons: Shem, Ham, and Japheth.`,
      `Now the earth was corrupt before God and filled with unrighteousness. Thus the Lord God looked upon the earth, and indeed it was corrupt; for all flesh corrupted their way on the earth. Then God said to Noah, “The end of all flesh has come before Me, for the earth is filled with unrighteousness through them; and behold, I will destroy them with the earth. Make yourself an ark of square timber. You shall make the ark in compartments, and cover it inside and outside with pitch. Thus you shall make the ark: three hundred cubits in length, fifty cubits in breadth, and thirty cubits in height. Now when you assemble the ark, you shall gradually finish it up to a cubit at the top, and set the door in its side. You shall make the ark with lower, second, and third stories. And behold, I am bringing a flood of water on the earth, to destroy from under heaven all flesh in which is the breath of life. Whatever is on the earth shall die. But I will establish My covenant with you; and you shall go into the ark—you, your sons, your wife, and your sons’ wives with you. From every living thing of all flesh you shall bring two of every kind into the ark, to keep them alive with you; they shall be male and female. Of the birds after their kind, of animals after their kind, and of every creeping thing on the earth after its kind, two of every kind, they will enter into the ark with you, male and female, to keep them alive. You shall also take for yourself all kinds of food to eat, and you shall gather it both for yourself and for them.” Thus Noah did according to all the Lord God commanded him, so he did.`,
      `The Flood Then the Lord God said to Noah, “Enter the ark, you and all your family, because I have seen you righteous before Me in this generation. You shall also bring with you into the ark the clean cattle by sevens, male and female; and the unclean cattle by twos, male and female; and the clean birds of heaven by twos, male and female, to keep seed alive on the face of all the earth. For after seven more days I will cause it to rain on the earth forty days and forty nights, and I will blot out from the face of the earth every living thing I made.” So Noah did all the Lord God commanded him.`,
      `Now Noah was six hundred years old when the flood of waters came on the earth.`,
      `In the six-hundredth year of Noah's life, in the second month, on the seventeenth day of the month, on that day, all the fountains of the great deep were broken up, and the floodgates of heaven were opened. Then it rained on the earth forty days and forty nights. On the very same day Noah and his wife, his sons, Shem, Ham, and Japheth, and their wives entered the ark. Also, all the wild animals after their kind, all cattle after their kind, every creeping thing moving upon the earth after its kind, and every bird after its kind, entered the ark with Noah, two by two, of all flesh in which is the breath of life. So those that entered, male and female of all flesh, went in as God commanded him. Then the Lord God shut him in the ark.`,
      `Now the flood was on the earth forty days and forty nights. The waters increased and lifted up the ark, and it rose high above the earth. So the waters prevailed and greatly increased on the earth, and the ark moved about on the surface of the waters. The waters prevailed exceedingly on the earth, and all the high mountains under the whole heaven were covered. The waters prevailed fifteen cubits upward, and covered all the high mountains. And all flesh died that moves on the earth: birds and cattle, wild animals, and every creeping thing that moves on the earth, and every man. Thus all things in whose nostrils was the breath of life, and everything on dry land, died. So He blotted out all living things on the face of the earth: both man and cattle, creeping things and the birds of heaven. They were blotted out from the earth. Only Noah and those with him in the ark remained alive. Now the waters prevailed on the earth one hundred and fifty days.`,
      `Then God remembered Noah, and whatever was with him in the ark: all the wild animals, all the cattle, all the birds, and all the creeping things. And God made a wind to pass over the earth, and the waters subsided. The fountains of the deep and the floodgates of heaven were also stopped, and the rain from heaven was restrained. And the waters receded continually from the earth. At the end of the hundred and fifty days the waters decreased. Then the ark rested in the seventh month, on the seventeenth day of the month, on the mountains of Ararat. And the waters decreased continually until the tenth month. In the tenth month, on the first day of the month, the tops of the mountains were seen.`,
      `So it came to pass, at the end of forty days, Noah opened the window of the ark he had made. Then he sent out a raven, which kept going to and fro until the waters dried up from the earth. He also sent out from himself a dove, to see if the waters had receded from the face of the ground. But the dove found no resting place for the sole of her foot, and she returned to him in the ark, for the waters were on the face of the whole earth. So he put out his hand and took her, and brought her to himself in the ark. Then he waited yet another seven days, and again he sent out the dove from the ark. The dove returned to him in the evening, and behold, a freshly plucked olive leaf was in her mouth; and Noah knew the waters had receded from the earth. So he waited yet another seven days and again sent out the dove; however, she did not return to him any more. And it came to pass in the six hundred and first year of Noah's life, in the first month, on the first day of the month, the waters were dried up from the earth; and Noah removed the covering of the ark and looked, and indeed, the surface of the ground was dry. Now in the second month, on the twenty- seventh day of the month, the earth was dried.`,
      `Then the Lord God spoke to Noah, saying, 6“Go out of the ark, you and your wife, and your sons and their wives with you. Also, bring out with you every living thing of all flesh: birds and cattle and every creeping thing that moves upon the earth, so they may abound on the earth, and increase and multiply on the earth.” So Noah went out, along with his wife and his sons and their wives. Every animal, every bird, and every creeping thing that moves upon the earth, according to their kind, went out of the ark. Then Noah built an altar to God, and took of every clean animal and of every clean bird, and offered whole burnt offerings on the altar. So the Lord God smelled a sweet aroma. Then the Lord God thought it over and said, “I will never again curse the earth because of man's works, although the mind of man is diligently involved with evil things from his youth; nor will I again destroy every living thing as I have done. While the earth remains, seedtime and harvest, cold and heat, summer and spring shall not cease by day or by night.”`,
    ],
  },
  {
    day: 5,
    title: 'Abraham',
    ornamentName: 'Constellation of Stars',
    bibleVerses: 'Genesis 12:1-7, 15:1-6, 17:1-9',
    readingText: [
      `Now the Lord said to Abram, “Get out of your country, from your kindred and from your father's house, to a land I will show you. I will make you a great nation; I will bless you and make your name great; and you shall be a blessing. I will bless those who bless you, and curse those who curse you; and in you all the tribes of the earth shall be blessed.” Then Abram departed as the Lord said to him, and Lot went with him. Now Abram was seventy-five years old when he de-parted from Haran. So Abram took Sarai his wife and Lot his brother's son and all their possessions and every soul they acquired in Haran, and they departed for the land of Canaan. Thus they came to the land of Canaan. Abram passed through the land to the place of Shechem, as far as the oak of Moreh. And the Canaanites were then in the land. Then the Lord appeared to Abram and said, “To your seed I will give this land.” And there Abram built an altar to the Lord, who appeared to him.`,
      `After these things the Word of the Lord came to Abram in a vision, saying, “Do not be afraid, Abram. I am your shield and will be your exceedingly great reward.” But Abram said, “Lord, what will You give me, seeing I go childless, and the heir of my house is Eliezer of Damascus, the son of Masek, my domestic maidservant?” Then Abram said, “Look, You have given me no offspring; indeed, my household servant is my heir.” And immediately the Voice of the Lord came to him, saying, “This one shall not be your heir, but the One who will come from your own body shall be your heir.” Then He brought him outside and said to him, “Look now toward heaven, and count the stars if you are able to number them.” And He said to him, “So shall your seed be.” And Abram believed God, and He accounted it to him for righteousness.`,
      `When Abram was ninety-nine years old, the Lord appeared to Abram and said to him, “I am your God; be pleasing before Me and blameless. I will establish My covenant between Me and you, and will multiply you exceedingly.” Then Abram fell on his face, and God talked with him, saying, 4“As for Me, behold, My covenant is with you, and you shall be a father of many nations. No longer shall your name be called Abram, but your name shall be Abraham; for I have made you a father of many nations. I will make you exceedingly fruitful; and I will make nations of you, and kings shall come from you. I will establish My covenant between Me and you and your seed after you in their generations, for an everlasting covenant, to be your God and the God of your seed after you. Also I will give you and your seed after you the land you are occupying as a sojourner, all the land of Canaan, as an everlasting possession; and I will be their God.”`,
      `Then God said to Abraham, “As for you, you shall keep My covenant, you and your seed after you throughout their generations.`,
    ],
  },
  {
    day: 6,
    title: 'Sacrifice of Isaac',
    ornamentName: 'Altar',
    bibleVerses: 'Genesis 22:1-18',
    readingText: [
      `Now it came to pass after these things that God tested Abraham, and said to him, “Abraham! Abraham!” And he said, “Here I am.” Then He said, “Take now your beloved son, Isaac, whom you love, and go to the land of Moriah, and offer him there as a whole burnt offering on one of the mountains I tell you.”`,
      `So Abraham rose early in the morning and saddled his donkey; and took two of his young men with him, and Isaac his son; and he split firewood for the whole burnt offering, and arose and went to the place God told him. Then on the third day Abraham lifted his eyes and saw the place afar off. Thus Abraham said to his young men, “Stay here with the donkey; the lad and I will go yonder and worship, and we will come back to you.”`,
      `So Abraham took the firewood of the whole burnt offering and laid it on Isaac his son. Then he took the fire in his hand, and a knife, and the two of them went together. Then Isaac spoke to Abraham his father and said, “My father.” And he said, “Here I am, my son.” Then he said, “Look, the fire and the firewood, but where is the sheep for a whole burnt offering?” And Abraham said, “My son, God will provide for Himself the sheep for a whole burnt offering.” So the two of them went together. They came to the place where God had told him. And Abraham built an altar there and placed the firewood in order; and he bound Isaac his son hand and foot and laid him on the altar, upon the firewood.`,
      `Then Abraham stretched out his hand and took the knife to slay his son. But the Angel of the Lord called to him from heaven and said, “Abraham! Abraham!” So he said, “Here I am.” He then replied, “Do not lay your hand on the lad, or do anything to him, for now I know you fear God, since for My sake you have not spared your beloved son.” Then Abraham lifted his eyes and looked, and there behind him a ram was caught in a thicket by its horns. So he brought it for a whole burnt offering in the place of his son. Thus Abraham called the name of the place The-Lord-Has-Appeared; as it is said to this day, “In the mountain the Lord was seen.”`,
      `Then the Angel of the Lord called to Abraham a second time out of heaven, and said, “By Myself I have sworn, says the Lord, because you did this thing, and for My sake did not spare your beloved son, I will certainly bless you, and assuredly multiply your seed as the stars of heaven and as the sand on the seashore; and your seed shall inherit the cities of their enemies. In your seed all the nations of the earth shall be blessed, because you obeyed My voice.”`,
    ],
  },
  {
    day: 7,
    title: `Jacob's Ladder`,
    ornamentName: `Ladder`,
    bibleVerses: 'Genesis 28:10-17',
    readingText: [
      `Now Jacob went out from the Well of Oath and went toward Haran. So he came to a certain place and stayed there all night, because the sun had set. Then he took one of the stones of that place and put it at his head, and he lay down in that place to sleep. Then he dreamed, and behold, a ladder was set up on the earth, and its top reached to heaven; and there the angels of God were ascending and descending on it. So behold, the Lord stood above it and said, “I am the Lord God of Abraham your father and the God of Isaac. Do not fear, the land on which you lie I will give to you and your seed. Also, your seed shall be as the dust of the earth; you shall spread abroad to the west and the east, to the north and the south; and in you and in your seed all the tribes of the earth shall be blessed. Behold, I am with you and will keep you wherever you go, and will bring you back to this land; for I will not leave you until I have done what I have spoken to you.”`,
      `Then Jacob awoke from his sleep and said, “The Lord is in this place, and I did not know it.” So he was afraid and said, “How awesome is this place! This is none other than the house of God, and this is the gate of heaven.”`,
    ],
  },
  {
    day: 8,
    title: `Israel’s 12 Sons`,
    ornamentName: `Coat of Many Colors`,
    bibleVerses: 'Genesis 37:3-36',
    readingText: [
      `Now Israel loved Joseph more than all his sons, because he was the son of his old age. He also made him a tunic of many colors. But when his brothers saw that their father loved him more than all his brothers, they hated him and could not speak civilly to him.`,
      `Then Joseph had a dream, and reported it to his brothers. Thus he said to them, “Hear this dream I dreamed: There we were, binding sheaves in the field. Then behold, my sheaf arose and also stood upright; and indeed your sheaves stood all around and bowed down to my sheaf.” So his brothers said to him, “Shall you indeed reign over us? Or shall you indeed have dominion over us?” So they hated him even more for his dreams and for his words.`,
      `Then he dreamed still another dream and told it to his brothers, and said, “Look, I have dreamed another dream. And this time, the sun, the moon, and the eleven stars bowed down to me.” So he told it to his father and his brothers; and his father rebuked him and said to him, “What is this dream you have dreamed? Shall your mother and I and your brothers indeed come and bow down on the ground before you?” And his brothers envied him, but his father kept the matter in mind.`,
      `Then his brothers went to feed their father's flock in Shechem. And Israel said to Joseph, “Are not your brothers shepherding the sheep in Shechem? Come, I will send you to them.” So he said to him, “Here I am.” Then Israel said to him, “Go and see if it is well with your brothers and well with the sheep, and bring back word to me.” So he sent him out of the Valley of Hebron, and he went to Shechem.`,
      `Now a certain man found him, and there he was, wandering in the field. So the man asked him, saying, “What are you seeking?” He replied, “I am looking for my brothers. Tell me where they are feeding their sheep.” The man said to him, “They have departed from here, for I heard them say, ‘Let us go to Dothan.”’ So Joseph went after his brothers and found them in Dothan. Now when they saw him afar off, even before he came near them, they conspired against him to kill him. Then they said to one another, “Look, this dreamer is coming. Come therefore, let us now kill him and cast him into some pit; and we shall say, ‘Some wild beast has devoured him.’ We shall see what will become of his dreams.”`,
      `But Reuben heard it, and he delivered him out of their hands; and said, “Let us not kill him.” Again, Reuben said to them, “Shed no blood, but cast him into this pit in the desert; and do not lay a hand on him”—that he might deliver him out of their hands, and bring him back to his father. So it came to pass, when Joseph came to his brothers, they stripped the tunic of many colors off him. Then they took him and cast him into a pit, which was empty; for there was no water in it.`,
      `They then sat down to eat a meal, and lifted their eyes and looked, and there was a company of Ishmaelite wayfarers coming from Gilead with their camels bearing spices, balm, and myrrh, on their way to carry them down to Egypt. So Judah said to his brothers, “What profit is there if we kill our brother and conceal his blood? Come and let us sell him to the Ishmaelites, but let not our hand be upon him; for he is our brother and our flesh”; and his brothers listened. Thus the Midianite traders passed by, and the brothers pulled Joseph up and lifted him out of the pit; and they sold him to the Ishmaelites for twenty pieces of gold. So they took Joseph to Egypt. Then Reuben returned to the pit, and when he saw Joseph was not in there, he tore his clothes. So he returned to his brothers and said, “The lad is not there; and I, where shall I go?”`,
      `Thus they took Joseph's tunic, killed a kid of the goats, and dipped the tunic in the blood. Then they sent the tunic of many colors, and had it brought to their father and said, “We found this. Do you know whether it is your son's tunic or not?” So he recognized it and said, “This is my son's tunic. A wild animal has devoured Joseph and carried him off.” Then Jacob tore his clothes, put sackcloth on his waist, and mourned for his son many days. Thus all his sons and daughters arose to comfort him; but he refused to be comforted, and he said, “I shall go down into the grave to my son in mourning.” So his father wept for him. Now the Midianites had sold him in Egypt to Potiphar, an officer of Pharaoh and captain of the guard.`,
    ],
  },
  {
    day: 9,
    title: `Joseph’s Elevation`,
    ornamentName: `Cows`,
    bibleVerses:
      'Genesis 41:1-16,25-34,36-37,39-44,56-57, 42:1-8,13-15,21-26, 43:1-5,11-17,26-31, 45:1-16',
    readingText: [
      `Then it came to pass, at the end of two full years, that Pharaoh had a dream; and behold, he stood by the river. Suddenly there came up out of the river seven cows, fine-looking and fat; and they fed in the meadow. Then behold, seven other cows came up after them out of the river, ugly and gaunt, and stood by the other cows on the bank of the river. But the ugly and gaunt cows ate up the seven fine-looking and fat cows. So Pharaoh awoke. He slept and dreamed a second time; and suddenly seven ears of corn came up on one stalk, plump and good. Then behold, seven ears of corn, thin and blighted by the east wind, sprang up after them. But the seven thin ears of corn devoured the seven plump and full ears. So Pharaoh awoke, and indeed, it was a dream.`,
      `Now it came to pass in the morning that his spirit was troubled, and he sent and called for all the interpreters of Egypt and all its wise men. Thus Pharaoh told them his dreams, but there was no one who could interpret them for Pharaoh. Then the cupbearer spoke to Pharaoh, saying, “I remember my sin this day. When Pharaoh was angry with his servants, and put me in custody in the house of the chief bodyguard, both myself and the chief baker, we each had a dream in one night, both he and I. Each had a dream regarding himself. Now there was with us a young Hebrew servant of the chief bodyguard, and we related our dreams to him; and he interpreted them for us. And it came to pass, just as he interpreted for us, so it happened. He restored me to my office, but he hanged him.”`,
      `Then Pharaoh sent and called Joseph, and they brought him quickly out of the dungeon; and he shaved, changed his clothing, and came to Pharaoh. Thus Pharaoh said to Joseph, “I had a dream, and there is no one who can interpret it. But I heard it said of you that you can understand a dream, to interpret it.” So Joseph answered Pharaoh, saying, “It is not in me; God will give Pharaoh an answer of peace.”`,
      `Then Joseph said to Pharaoh, “The dreams of Pharaoh are one; God has shown Pharaoh what He is about to do: The seven good cows are seven years, and the seven good ears of corn are seven years; the dreams are one. But the seven thin and ugly cows that came up after them are seven years, and the seven empty heads blighted by the east wind are seven years of famine. This is the thing I have spoken to Pharaoh. God has shown Pharaoh what He is about to do. Indeed, seven years of great plenty will come throughout all the land of Egypt; but after them seven years of famine will arise, and all the plenty will be forgotten in the land of Egypt; and the famine will deplete the land. So the plenty will not be known in the land because of the famine following, for it will be very severe. Now the dream was repeated to Pharaoh twice because the thing is established by God, and God will shortly bring it to pass. Now therefore, let Pharaoh select a sensible and intelligent man, and set him over the land of Egypt. Let Pharaoh do this, and let him appoint governors over the land, to collect one-fifth of the produce of the land of Egypt in the seven plentiful years.`,
      `That food shall then be as a reserve in the land for the seven coming years of famine in the land of Egypt, that the land may not perish during the famine.” Joseph Made Ruler of Egypt Now this advice was good in the eyes of Pharaoh and in the eyes of all his servants.`,
      `Then Pharaoh said to Joseph, “Inasmuch as God has shown you all this, there is no one as sensible and intelligent as you. You shall be over my house, and all my people shall be ruled according to your word; only in regard to the throne will I be greater than you.” So Pharaoh said to Joseph, “See, I have set you over all the land of Egypt.”`,
      `Then Pharaoh took the signet ring off his hand and put it on Joseph's hand; and he clothed him in garments of fine linen and put a gold chain around his neck. Then he had him ride in the second of his chariots; and they cried out before him, “Bow the knee!” So he set him over all the land of Egypt. Pharaoh also said to Joseph, “I am Pharaoh, and without your consent no man may lift his hand or foot in all the land of Egypt.”`,
      `The famine was over all the face of the earth, and Joseph opened all the storehouses and sold to the Egyptians. Then all countries also came to Joseph in Egypt to buy grain, because the famine was severe in all the earth.`,
      `When Jacob found out there was grain for sale in Egypt, he said to his sons, “Why are you standing idle?” Then he said, “Indeed, I heard there is grain in Egypt; go down there and buy for us there, that we may live and not die.” So Joseph's ten brothers went down to buy grain in Egypt. But Jacob did not send Joseph's brother Benjamin with his brothers, for he said, “Lest some calamity befall him.”`,
      `Thus the sons of Israel went to buy grain with those who were going there, for the famine was in the land of Canaan. Now Joseph was governor over the land; and it was he who sold to all the people of the land. So Joseph's brothers came and bowed down before him with their faces to the ground. Joseph saw his brothers and recognized them, but he acted as a stranger to them and spoke roughly to them. Then he said to them, “Where do you come from?” And they said, “From the land of Canaan to buy food.” So Joseph recognized his brothers, but they did not recognize him.`,
      `Then they said, “Your servants are twelve brothers, the sons of one man in the land of Canaan; and in fact, the youngest is with our father today, and one is no more.” But Joseph said to them, “It is as I spoke to you, namely, ‘You are spies!’ In this manner you shall be manifested: By the life of Pharaoh, you shall not leave this place unless your youngest brother comes here.`,
      `Then they said to one another, “We are truly guilty concerning our brother, for we saw the anguish of his soul when he pleaded with us, and we would not hear; therefore this distress has come upon us.” Reuben then answered them, saying, “Did I not speak to you, saying, ‘Do not sin against the boy,’ but you would not listen? Therefore, behold, his blood is now required of us.” But they did not know Joseph understood them, for he spoke to them through an interpreter.`,
      `Then Joseph turned himself away from them and wept. So he returned to them again, and talked with them; and took Simeon from them, and bound him before their eyes. Joseph then gave a command to fill their sacks with grain, to restore every man's money to his sack, and to give them provisions for the journey. Thus he did for them.`,
      `So they loaded their donkeys with the grain and departed from there.`,
    ],
  },
  {
    day: 10,
    title: `Israel’s Blessing and Prophecy on Judah`,
    ornamentName: `Lion`,
    bibleVerses: 'Genesis 49:1-2,8-12',
    readingText: [
      `Now Jacob called his sons and said, “Gather together, that I may tell you what shall befall you in the last days: `,
      `“Gather together and hear, you sons of Jacob, And listen to Israel your father.`,
      `Judah, you are he whom your brothers shall praise; Your hand shall be on the neck of your enemies; Your father's sons shall bow down before you. Judah is a lion's cub; From being a shoot, my son, you have grown up. He bows down, and slept as a lion and a cub; And who shall rouse him? The scepter shall not depart from Judah, Nor a lawgiver from his loins, Until Shiloh comes; And to Him shall be the expectation of the nations. Binding his colt to a vine, And his donkey's colt to its branch, He will wash his garments in wine, And his clothes in the blood of grapes. His eyes are gladdened from the wine, And his teeth are whiter than milk.`,
    ],
  },
  {
    day: 11,
    title: `The Infant Moses`,
    ornamentName: `Basket`,
    bibleVerses: 'Exodus 1:8-14,22, 2:1-10',
    readingText: [
      `But there arose a new king over Egypt who knew not Joseph. Then he said to his nation, “Look, the race of the children of Israel is a great multitude and is stronger than we; come, let us outwit them, lest they multiply, and it happen in the event of war that they also join our enemies and fight against us and so escape out of the land.” Therefore he set taskmasters over them to afflict them in their works; and they built for Pharaoh strong cities —Pithom and Raamses and On, which is Heliopolis. But the more they humbled them, the more they multiplied and grew; and the Egyptians greatly abhorred the children of Israel. So the Egyptians tyrannized the children of Israel by force. They made their lives bitter with hard labor—in mortar, in brick, and in all manner of service in the field. All their labor in which they made them serve was by violence.`,
      `So Pharaoh commanded all his people, saying, “Every male born to the Hebrews you shall cast into the river, but every female you shall save alive.”`,
      `Now a man of the house of Levi went and took as wife a daughter of Levi. So the woman conceived and bore a son; and seeing he was a beautiful child, they hid him three months. But when she could no longer hide him, she took an ark of bulrushes, daubed it with asphalt, put the child in it, and laid it in the reeds by the river's bank. Now his sister was watching from a distance to learn what would be done with him.`,
      `Then the daughter of Pharaoh came down to bathe at the river, and her maidens walked along the riverside; and seeing the ark among the reeds, she sent a maid to get it. So when she opened the ark, she saw the child crying, and the daughter of Pharaoh had compassion on him and said, “This is one of the Hebrews’ children.” Then his sister said to Pharaoh's daughter, “Shall I go and call a nurse for you from the Hebrew women, that she may nurse the child for you?” So Pharaoh's daughter said to her, “Go.” Then the maiden went and called the child's mother. Pharaoh's daughter then said to her, “Take this child and nurse him for me, and I will pay you.” So the woman took the child and nursed him. Now when the boy was grown, she brought him to Pharaoh's daughter, and he became her son; and she called his name Moses, saying, “Because I drew him out of the water.”`,
    ],
  },
  {
    day: 12,
    title: `Moses and the Burning Bush`,
    ornamentName: `Burning Bush`,
    bibleVerses: 'Read Exodus 3:1-20',
    readingText: [
      `Now Moses was tending the sheep of Jethro his father-in-law, the priest of Midian. Then he led them to the back of the desert and came to Horeb, the mountain of God. Then the Angel of the Lord appeared to him in a flame of fire from the midst of a bush. So he saw the bush burning with fire, but the bush was not consumed. So Moses said, “I will now turn aside and see this great sight, why the bush is not consumed.”`,
      `When therefore the Lord saw him turn aside to look, God called to him from the midst of the bush and said, “Moses! Moses!” Then he said, “Here I am.” So He said, “Do not come any closer. Take your sandals off your feet, for the place where you stand is holy ground.” Moreover He said, “I am the God of your father—the God of Abraham, the God of Isaac, and the God of Jacob.” Moses then hid his face, for he was afraid to look at God.`,
      `Then the Lord said, “Indeed, I have seen the affliction of My people in Egypt, and have heard their cry because of their taskmasters; for I know their sorrow. So I came down to deliver them out of the hand of the Egyptians and to bring them up from that land to a good and large land, to a land flowing with milk and honey, to the place of the Canaanites, the Hittites, the Amorites, the Perizzites, the Gergesites, the Hivites, and the Jebusites. Now therefore, behold, the cry of the children of Israel has come to Me, and I have also seen the affliction with which the Egyptians oppress them. Come now, I will send you to Pharaoh, to bring My people, the children of Israel, out of the land of Egypt.”`,
      `But Moses said to God, “Who am I to go to Pharaoh, king of Egypt, to bring the children of Israel out of the land of Egypt?” Then God said to Moses, “I will be with you, and this shall be a sign to you that I have sent you: When you have brought the people out of Egypt, you shall serve God on this mountain.” So Moses said to God, “Indeed, when I go to the children of Israel and say to them, ‘The God of your fathers sent me to you,’ and they ask me, ‘What is His name?’ what shall I tell them?”`,
      `Then God said to Moses, “I AM the Existing One.” He also said, “Thus you shall say to the children of Israel: ‘The Existing One sent me to you.’ ” Moreover God said to Moses again, “Thus you shall say to the children of Israel: ‘The Lord God of your fathers—the God of Abraham, the God of Isaac, and the God of Jacob—sent me to you.’ This is My name forever, and My memorial to all generations. Go then, and gather the elders of the children of Israel together and say to them, ‘The Lord God of your fathers—the God of Abraham, the God of Isaac, and the God of Jacob—appeared to me, saying, “I have surely looked upon you and all the things that happened to you in Egypt; and I will bring you up out of the affliction of Egypt to the land of the Canaanites, the Hittites, the Amorites, the Perizzites, the Gergesites, the Hivites, and the Jebusites, to a land flowing with milk and honey.’”`,
      `“Then they will heed your voice; and you shall go, you and the elders of Israel, to the king of Egypt; and you shall say to him, ‘The God of the Hebrews met with us; and now, let us go three days’ journey into the desert to sacrifice to our God.’ But I know Pharaoh the king of Egypt will not let you go, not even by a mighty hand. Thus I will stretch out My hand and strike the Egyptians with all My wonders which I will work among them; and after that he will let you go."`,
    ],
  },
];
