export interface ReadingDay {
  day: number;
  title: string;
  ornamentName: string;
  bibleVerses: string;
  readingText: string[];
}
// First day in 2021 is Nov. 15
export const readings: ReadingDay[] = [
  {
    day: 1,
    title: 'Creation of Universe',
    ornamentName: 'Sun',
    bibleVerses: 'Genesis 1-2:4',
    readingText: [
      `In the beginning God made heaven and earth. The earth was invisible and unfinished; and darkness was over the deep. The Spirit of God was hovering over the face of the water. Then God said, “Let there be light”; and there was light. God saw the light; it was good; and God divided the light from the darkness. God called the light Day; the darkness He called Night; and there was evening and morning, one day.`,
      `Then God said, “Let there be a firmament in the midst of the water, and let it divide the water from the water”; and it was so. Thus God made the firmament, and God divided the water under the firmament from the water above the firmament. So God called the firmament Heaven, and God saw that it was good; and there was evening and morning, the second day.`,
      `Then God said, “Let the water under heaven be gathered together into one place, and let the dry land appear”; and it was so. The water under heaven was gathered into its places, and the dry land appeared. So God called the dry land Earth, and the gathering together of the waters He called Seas; and God saw that it was good. Then God said, “Let the earth bring forth the herb of grass, bearing seed according to its kind and likeness. Let the fruit tree bear fruit, whose seed is in itself according to its kind on earth.” It was so. Thus the earth brought forth the herb of grass, bearing seed according to its kind and likeness. The fruit tree bore fruit, whose seed is in itself according to its kind on earth. God saw that it was good. So evening and morning were the third day.`,
      `Then God said, “Let there be lights in the firmament of heaven for illumination to divide day from night. Let them be for signs and seasons, and for days and years. Let them be for illumination in the firmament of heaven to give light on the earth.” It was so. Then God made two great lights: the greater light to rule the day, and the lesser light to rule the night. He made the stars also. God set them in the firmament of heaven to give light on the earth, and to rule over the day and over the night, and to divide the light from the darkness. God saw that it was good. So evening and morning were the fourth day.`,
      `Then God said, “Let the waters bring forth creatures having life, and let birds fly above the earth across the face of heaven's firmament.” It was so. Thus God made great sea creatures and every living thing that moves with which the waters abounded, according to their kind, and every winged bird according to its kind. God saw that it was good. God blessed them, saying, “Be fruitful and multiply, and fill the waters in the seas, and let birds multiply on earth.” So evening and morning were the fifth day.`,
      `Then God said, “Let the earth bring forth the living creature according to its kind: the quadrupeds, the creeping things, and the wild animals of the earth according to their kind.” It was so. So God made the wild animals of the earth according to their kind, the cattle according to their kind, and all the creeping things on earth according to their kind. God saw that it was good. Then God said, “Let Us make man in Our image, according to Our likeness. Let them have dominion over the fish of the sea, over the birds of heaven, over the cattle, and over all the earth, and over every creeping thing that moves on the earth.” So God made man; in the image of God He made him; male and female He made them. Then God blessed them; and God said to them, “Be fruitful and multiply; fill the earth and subdue it, and have dominion over the fish of the sea, over the birds of heaven, and over every living thing that moves on the earth.”`,
      `Then God said, “Behold, I have given you every seed-bearing herb that sows seed on the face of all the earth, and every tree whose fruit yields seed; to you it shall be for food. I also give every green plant as food for all the wild animals of the earth, for all the birds of heaven, and for everything that creeps on the earth in which is the breath of life.” It was so. Then God saw everything He had made, and indeed, it was very good. So evening and morning were the sixth day.`,
      `Thus heaven and earth and all their adornment were finished. And on the seventh day God finished the works He made, and He rested on the seventh day from all the works He made. Then God blessed the seventh day and sanctified it, because in it He rested from all His works God began to make.`,
      `This is the book of the genesis of heaven and earth when they were made, in the day the Lord God made heaven and earth`,
    ],
  },
  {
    day: 2,
    title: 'Creation of Man',
    ornamentName: 'Two People',
    bibleVerses: 'Genesis 2:4-25',
    readingText: [
      `This is the book of the genesis of heaven and earth when they were made, in the day the Lord God made heaven and earth, before any plant of the field was on earth and before any herb of the field sprang up. For God had not sent rain on the earth, and there was no man to till the ground; but a fountain came up from the ground and watered the whole face of the earth. Then God formed man out of dust from the ground, and breathed in his face the breath of life; and man became a living soul.`,
      `Then the Lord God planted a garden eastward in Eden, and there He put the man He formed. Besides this, God caused every tree beautiful to the sight and good for food to grow from the ground. Also, in the middle of the garden were the tree of life and the tree of learning the knowledge of good and evil. Now a river went out of Eden to water the garden, and from there it separated into four heads. The name of the first is Pishon. It circles all the land of Havilah, where there is gold. And the gold of that land is good. The carbuncle and the emerald are there as well. The name of the second river is Gihon. It circles all the land of Ethiopia. The name of the third river is Tigris. It flows over against the Assyrians. And the fourth river is Euphrates.`,
      `Then the Lord God took the man He formed and put him in the garden to tend and keep it. And the Lord God commanded Adam, saying, “You may eat food from every tree in the garden; but from the tree of the knowledge of good and evil you may not eat; for in whatever day you eat from it, you shall die by death.”`,
      `And the Lord God said, “It is not good for man to be alone. I will make him a helper comparable to him.” Also, God formed out of the ground all the wild animals of the field and all the birds of heaven, and brought them to Adam to see what he would call them. Thus whatever Adam called each living creature, that was its name. So Adam gave names to all the cattle, to all the birds of heaven, and to all the wild animals of the field. But for Adam there was not found a helper comparable to him. Thus God brought a trance upon Adam, and he slept; and He took one of his ribs, and filled up the flesh in its place. Then the Lord God built the rib He took from Adam into a woman, and brought her to him. So Adam said, “This is now bone of my bones, and flesh of my flesh. She shall be called Woman, because she was taken out of Man. For this reason a man shall leave his father and mother and be joined to his wife; and the two shall become one flesh.” Now the two were naked, both Adam and his wife, and were not ashamed.`,
    ],
  },
  {
    day: 3,
    title: 'The Fall',
    ornamentName: 'Fruit',
    bibleVerses: 'Genesis 3:1-24',
    readingText: [
      `Now the serpent was more cunning than all the wild animals the Lord God made on the earth. And he said to the woman, “Has God indeed said, ‘You shall not eat from every tree of the garden’?” And the woman said to the serpent, “We may eat the fruit from the trees of the garden; but from the fruit of the tree in the middle of the garden, God said, ‘You shall not eat from it, nor shall you touch it, lest you die.’ ” Then the serpent said to the woman, “You shall not die by death. For God knows in the day you eat from it your eyes will be opened, and you will be like gods, knowing good and evil.” So when the woman saw the tree was good for food, was pleasant to the eyes, and a tree beautiful to contemplate, she took its fruit and ate. She also gave it to her husband with her, and he ate. Then the eyes of the two were opened, and they knew they were naked. So they sewed fig leaves together and made themselves coverings.`,
      `Then they heard the voice of the Lord God walking in the garden that afternoon, and Adam and his wife hid themselves within the tree in the middle of the garden from the presence of the Lord God. So the Lord God called Adam and said to him, “Adam, where are you?” He replied, “I heard Your voice as You were walking in the garden, and I was afraid because I was naked; so I hid myself.” Thus He said, “Who said you were naked? Have you eaten from the one tree from which I commanded you not to eat?” Then Adam said, “The woman You gave me, gave me of the tree, and I ate.” So the Lord God said to the woman, “What is this you have done?” The woman said, “The serpent deceived me, and I ate.” Thus the Lord God said to the serpent, “Because you have done this, you are cursed more than all cattle, and more than all the wild animals of the earth. On your breast and belly you shall go, and you shall eat dust all the days of your life. I will put enmity between you and the woman, and between your seed and her seed. He shall bruise your head, and you shall be on guard for His heel.”`,
      `To the woman He said, “I will greatly multiply your pain and your groaning, and in pain you shall bring forth children. Your recourse will be to your husband, and he shall rule over you.” Then to Adam He said, “Because you heeded the voice of your wife, and ate from the one tree of which I commanded you, saying, ‘You shall not eat from it,’ cursed is the ground in your labors. In toil you shall eat from it all the days of your life. Both thorns and thistles it shall bring forth for you, and you shall eat the herb of the field. In the sweat of your face you shall eat bread till you return to the ground from which you were taken. Earth you are, and to earth you shall return.” So Adam called his wife's name Life, because she was the mother of all living.`,
      `Also for Adam and his wife the Lord God made garments of skin, and clothed them. Then the Lord God said, “Behold, the man has become like one of Us, to know good and evil. Now, lest he put out his hand and take also of the tree of life, and eat, and live forever—” therefore the Lord God sent him out of the garden of pleasure to cultivate the ground from which he was taken. So He cast out Adam, and made him dwell opposite the garden of pleasure. He then stationed the cherubim and the fiery sword which turns every way to guard the way to the tree of life.`,
    ],
  },
  {
    day: 4,
    title: 'Noah',
    ornamentName: 'Rainbow',
    bibleVerses: 'Genesis 6:9-7:6, 7:11-24, 8:1-24',
    readingText: [
      `This is the genealogy of Noah. Noah was a righteous man, who was perfect in his generation and well-pleasing to God. So Noah begot three sons: Shem, Ham, and Japheth.`,
      `Now the earth was corrupt before God and filled with unrighteousness. Thus the Lord God looked upon the earth, and indeed it was corrupt; for all flesh corrupted their way on the earth. Then God said to Noah, “The end of all flesh has come before Me, for the earth is filled with unrighteousness through them; and behold, I will destroy them with the earth. Make yourself an ark of square timber. You shall make the ark in compartments, and cover it inside and outside with pitch. Thus you shall make the ark: three hundred cubits in length, fifty cubits in breadth, and thirty cubits in height. Now when you assemble the ark, you shall gradually finish it up to a cubit at the top, and set the door in its side. You shall make the ark with lower, second, and third stories. And behold, I am bringing a flood of water on the earth, to destroy from under heaven all flesh in which is the breath of life. Whatever is on the earth shall die. But I will establish My covenant with you; and you shall go into the ark—you, your sons, your wife, and your sons’ wives with you. From every living thing of all flesh you shall bring two of every kind into the ark, to keep them alive with you; they shall be male and female. Of the birds after their kind, of animals after their kind, and of every creeping thing on the earth after its kind, two of every kind, they will enter into the ark with you, male and female, to keep them alive. You shall also take for yourself all kinds of food to eat, and you shall gather it both for yourself and for them.” Thus Noah did according to all the Lord God commanded him, so he did.`,
      `The Flood Then the Lord God said to Noah, “Enter the ark, you and all your family, because I have seen you righteous before Me in this generation. You shall also bring with you into the ark the clean cattle by sevens, male and female; and the unclean cattle by twos, male and female; and the clean birds of heaven by twos, male and female, to keep seed alive on the face of all the earth. For after seven more days I will cause it to rain on the earth forty days and forty nights, and I will blot out from the face of the earth every living thing I made.” So Noah did all the Lord God commanded him.`,
      `Now Noah was six hundred years old when the flood of waters came on the earth.`,
      `In the six-hundredth year of Noah's life, in the second month, on the seventeenth day of the month, on that day, all the fountains of the great deep were broken up, and the floodgates of heaven were opened. Then it rained on the earth forty days and forty nights. On the very same day Noah and his wife, his sons, Shem, Ham, and Japheth, and their wives entered the ark. Also, all the wild animals after their kind, all cattle after their kind, every creeping thing moving upon the earth after its kind, and every bird after its kind, entered the ark with Noah, two by two, of all flesh in which is the breath of life. So those that entered, male and female of all flesh, went in as God commanded him. Then the Lord God shut him in the ark.`,
      `Now the flood was on the earth forty days and forty nights. The waters increased and lifted up the ark, and it rose high above the earth. So the waters prevailed and greatly increased on the earth, and the ark moved about on the surface of the waters. The waters prevailed exceedingly on the earth, and all the high mountains under the whole heaven were covered. The waters prevailed fifteen cubits upward, and covered all the high mountains. And all flesh died that moves on the earth: birds and cattle, wild animals, and every creeping thing that moves on the earth, and every man. Thus all things in whose nostrils was the breath of life, and everything on dry land, died. So He blotted out all living things on the face of the earth: both man and cattle, creeping things and the birds of heaven. They were blotted out from the earth. Only Noah and those with him in the ark remained alive. Now the waters prevailed on the earth one hundred and fifty days.`,
      `Then God remembered Noah, and whatever was with him in the ark: all the wild animals, all the cattle, all the birds, and all the creeping things. And God made a wind to pass over the earth, and the waters subsided. The fountains of the deep and the floodgates of heaven were also stopped, and the rain from heaven was restrained. And the waters receded continually from the earth. At the end of the hundred and fifty days the waters decreased. Then the ark rested in the seventh month, on the seventeenth day of the month, on the mountains of Ararat. And the waters decreased continually until the tenth month. In the tenth month, on the first day of the month, the tops of the mountains were seen.`,
      `So it came to pass, at the end of forty days, Noah opened the window of the ark he had made. Then he sent out a raven, which kept going to and fro until the waters dried up from the earth. He also sent out from himself a dove, to see if the waters had receded from the face of the ground. But the dove found no resting place for the sole of her foot, and she returned to him in the ark, for the waters were on the face of the whole earth. So he put out his hand and took her, and brought her to himself in the ark. Then he waited yet another seven days, and again he sent out the dove from the ark. The dove returned to him in the evening, and behold, a freshly plucked olive leaf was in her mouth; and Noah knew the waters had receded from the earth. So he waited yet another seven days and again sent out the dove; however, she did not return to him any more. And it came to pass in the six hundred and first year of Noah's life, in the first month, on the first day of the month, the waters were dried up from the earth; and Noah removed the covering of the ark and looked, and indeed, the surface of the ground was dry. Now in the second month, on the twenty- seventh day of the month, the earth was dried.`,
      `Then the Lord God spoke to Noah, saying, 6“Go out of the ark, you and your wife, and your sons and their wives with you. Also, bring out with you every living thing of all flesh: birds and cattle and every creeping thing that moves upon the earth, so they may abound on the earth, and increase and multiply on the earth.” So Noah went out, along with his wife and his sons and their wives. Every animal, every bird, and every creeping thing that moves upon the earth, according to their kind, went out of the ark. Then Noah built an altar to God, and took of every clean animal and of every clean bird, and offered whole burnt offerings on the altar. So the Lord God smelled a sweet aroma. Then the Lord God thought it over and said, “I will never again curse the earth because of man's works, although the mind of man is diligently involved with evil things from his youth; nor will I again destroy every living thing as I have done. While the earth remains, seedtime and harvest, cold and heat, summer and spring shall not cease by day or by night.”`,
    ],
  },
  {
    day: 5,
    title: 'Abraham',
    ornamentName: 'Constellation of Stars',
    bibleVerses: 'Genesis 12:1-7, 15:1-6, 17:1-9',
    readingText: [
      `Now the Lord said to Abram, “Get out of your country, from your kindred and from your father's house, to a land I will show you. I will make you a great nation; I will bless you and make your name great; and you shall be a blessing. I will bless those who bless you, and curse those who curse you; and in you all the tribes of the earth shall be blessed.” Then Abram departed as the Lord said to him, and Lot went with him. Now Abram was seventy-five years old when he de-parted from Haran. So Abram took Sarai his wife and Lot his brother's son and all their possessions and every soul they acquired in Haran, and they departed for the land of Canaan. Thus they came to the land of Canaan. Abram passed through the land to the place of Shechem, as far as the oak of Moreh. And the Canaanites were then in the land. Then the Lord appeared to Abram and said, “To your seed I will give this land.” And there Abram built an altar to the Lord, who appeared to him.`,
      `After these things the Word of the Lord came to Abram in a vision, saying, “Do not be afraid, Abram. I am your shield and will be your exceedingly great reward.” But Abram said, “Lord, what will You give me, seeing I go childless, and the heir of my house is Eliezer of Damascus, the son of Masek, my domestic maidservant?” Then Abram said, “Look, You have given me no offspring; indeed, my household servant is my heir.” And immediately the Voice of the Lord came to him, saying, “This one shall not be your heir, but the One who will come from your own body shall be your heir.” Then He brought him outside and said to him, “Look now toward heaven, and count the stars if you are able to number them.” And He said to him, “So shall your seed be.” And Abram believed God, and He accounted it to him for righteousness.`,
      `When Abram was ninety-nine years old, the Lord appeared to Abram and said to him, “I am your God; be pleasing before Me and blameless. I will establish My covenant between Me and you, and will multiply you exceedingly.” Then Abram fell on his face, and God talked with him, saying, 4“As for Me, behold, My covenant is with you, and you shall be a father of many nations. No longer shall your name be called Abram, but your name shall be Abraham; for I have made you a father of many nations. I will make you exceedingly fruitful; and I will make nations of you, and kings shall come from you. I will establish My covenant between Me and you and your seed after you in their generations, for an everlasting covenant, to be your God and the God of your seed after you. Also I will give you and your seed after you the land you are occupying as a sojourner, all the land of Canaan, as an everlasting possession; and I will be their God.”`,
      `Then God said to Abraham, “As for you, you shall keep My covenant, you and your seed after you throughout their generations.`,
    ],
  },
  {
    day: 6,
    title: 'Sacrifice of Isaac',
    ornamentName: 'Altar',
    bibleVerses: 'Genesis 22:1-18',
    readingText: [
      `Now it came to pass after these things that God tested Abraham, and said to him, “Abraham! Abraham!” And he said, “Here I am.” Then He said, “Take now your beloved son, Isaac, whom you love, and go to the land of Moriah, and offer him there as a whole burnt offering on one of the mountains I tell you.”`,
      `So Abraham rose early in the morning and saddled his donkey; and took two of his young men with him, and Isaac his son; and he split firewood for the whole burnt offering, and arose and went to the place God told him. Then on the third day Abraham lifted his eyes and saw the place afar off. Thus Abraham said to his young men, “Stay here with the donkey; the lad and I will go yonder and worship, and we will come back to you.”`,
      `So Abraham took the firewood of the whole burnt offering and laid it on Isaac his son. Then he took the fire in his hand, and a knife, and the two of them went together. Then Isaac spoke to Abraham his father and said, “My father.” And he said, “Here I am, my son.” Then he said, “Look, the fire and the firewood, but where is the sheep for a whole burnt offering?” And Abraham said, “My son, God will provide for Himself the sheep for a whole burnt offering.” So the two of them went together. They came to the place where God had told him. And Abraham built an altar there and placed the firewood in order; and he bound Isaac his son hand and foot and laid him on the altar, upon the firewood.`,
      `Then Abraham stretched out his hand and took the knife to slay his son. But the Angel of the Lord called to him from heaven and said, “Abraham! Abraham!” So he said, “Here I am.” He then replied, “Do not lay your hand on the lad, or do anything to him, for now I know you fear God, since for My sake you have not spared your beloved son.” Then Abraham lifted his eyes and looked, and there behind him a ram was caught in a thicket by its horns. So he brought it for a whole burnt offering in the place of his son. Thus Abraham called the name of the place The-Lord-Has-Appeared; as it is said to this day, “In the mountain the Lord was seen.”`,
      `Then the Angel of the Lord called to Abraham a second time out of heaven, and said, “By Myself I have sworn, says the Lord, because you did this thing, and for My sake did not spare your beloved son, I will certainly bless you, and assuredly multiply your seed as the stars of heaven and as the sand on the seashore; and your seed shall inherit the cities of their enemies. In your seed all the nations of the earth shall be blessed, because you obeyed My voice.”`,
    ],
  },
  {
    day: 7,
    title: `Jacob's Ladder`,
    ornamentName: `Ladder`,
    bibleVerses: 'Genesis 28:10-17',
    readingText: [
      `Now Jacob went out from the Well of Oath and went toward Haran. So he came to a certain place and stayed there all night, because the sun had set. Then he took one of the stones of that place and put it at his head, and he lay down in that place to sleep. Then he dreamed, and behold, a ladder was set up on the earth, and its top reached to heaven; and there the angels of God were ascending and descending on it. So behold, the Lord stood above it and said, “I am the Lord God of Abraham your father and the God of Isaac. Do not fear, the land on which you lie I will give to you and your seed. Also, your seed shall be as the dust of the earth; you shall spread abroad to the west and the east, to the north and the south; and in you and in your seed all the tribes of the earth shall be blessed. Behold, I am with you and will keep you wherever you go, and will bring you back to this land; for I will not leave you until I have done what I have spoken to you.”`,
      `Then Jacob awoke from his sleep and said, “The Lord is in this place, and I did not know it.” So he was afraid and said, “How awesome is this place! This is none other than the house of God, and this is the gate of heaven.”`,
    ],
  },
];
