name: Deploy to S3

on:
  push:
    # branches: [ main ]

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install
      run: npm install
    
    - name: Build
      run: npm run build

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd terraform
        terraform init
    
    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
